// Code generated by ogen, DO NOT EDIT.

package cbnsapi

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetBucket implements GetBucket operation.
//
// GET /pools/default/buckets/{bucketName}
func (UnimplementedHandler) GetBucket(ctx context.Context, params GetBucketParams) (r *BucketInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBucketTerse implements GetBucketTerse operation.
//
// GET /pools/default/b/{bucketName}
func (UnimplementedHandler) GetBucketTerse(ctx context.Context, params GetBucketTerseParams) (r *TerseBucketInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetBuckets implements GetBuckets operation.
//
// GET /pools/default/buckets
func (UnimplementedHandler) GetBuckets(ctx context.Context) (r BucketsInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetDefaultPool implements GetDefaultPool operation.
//
// GET /pools/default
func (UnimplementedHandler) GetDefaultPool(ctx context.Context) (r *PoolInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// GetNodeServices implements GetNodeServices operation.
//
// GET /pools/default/nodeServices
func (UnimplementedHandler) GetNodeServices(ctx context.Context) (r *NodeServices, _ error) {
	return r, ht.ErrNotImplemented
}

// GetPools implements GetPools operation.
//
// GET /pools
func (UnimplementedHandler) GetPools(ctx context.Context) (r *PoolsInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// StreamBucketTerse implements StreamBucketTerse operation.
//
// GET /pools/default/bs/{bucketName}
func (UnimplementedHandler) StreamBucketTerse(ctx context.Context, params StreamBucketTerseParams) (r *TerseBucketInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// StreamDefaultPool implements StreamDefaultPool operation.
//
// GET /poolsStreaming/default
func (UnimplementedHandler) StreamDefaultPool(ctx context.Context) (r *PoolInfo, _ error) {
	return r, ht.ErrNotImplemented
}

// StreamNodeServices implements StreamNodeServices operation.
//
// GET /pools/default/nodeServicesStreaming
func (UnimplementedHandler) StreamNodeServices(ctx context.Context) (r *NodeServices, _ error) {
	return r, ht.ErrNotImplemented
}
