// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package gocbcorex

import (
	"context"
	"sync"
)

// Ensure, that kvClientFactoryMock does implement kvClientFactory.
// If this is not the case, regenerate this file with moq.
var _ kvClientFactory = &kvClientFactoryMock{}

// kvClientFactoryMock is a mock implementation of kvClientFactory.
//
//	func TestSomethingThatUseskvClientFactory(t *testing.T) {
//
//		// make and configure a mocked kvClientFactory
//		mockedkvClientFactory := &kvClientFactoryMock{
//			NewKvClientFunc: func(ctx context.Context, config *KvClientConfig) (KvClient, error) {
//				panic("mock out the NewKvClient method")
//			},
//		}
//
//		// use mockedkvClientFactory in code that requires kvClientFactory
//		// and then make assertions.
//
//	}
type kvClientFactoryMock struct {
	// NewKvClientFunc mocks the NewKvClient method.
	NewKvClientFunc func(ctx context.Context, config *KvClientConfig) (KvClient, error)

	// calls tracks calls to the methods.
	calls struct {
		// NewKvClient holds details about calls to the NewKvClient method.
		NewKvClient []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Config is the config argument value.
			Config *KvClientConfig
		}
	}
	lockNewKvClient sync.RWMutex
}

// NewKvClient calls NewKvClientFunc.
func (mock *kvClientFactoryMock) NewKvClient(ctx context.Context, config *KvClientConfig) (KvClient, error) {
	if mock.NewKvClientFunc == nil {
		panic("kvClientFactoryMock.NewKvClientFunc: method is nil but kvClientFactory.NewKvClient was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Config *KvClientConfig
	}{
		Ctx:    ctx,
		Config: config,
	}
	mock.lockNewKvClient.Lock()
	mock.calls.NewKvClient = append(mock.calls.NewKvClient, callInfo)
	mock.lockNewKvClient.Unlock()
	return mock.NewKvClientFunc(ctx, config)
}

// NewKvClientCalls gets all the calls that were made to NewKvClient.
// Check the length with:
//
//	len(mockedkvClientFactory.NewKvClientCalls())
func (mock *kvClientFactoryMock) NewKvClientCalls() []struct {
	Ctx    context.Context
	Config *KvClientConfig
} {
	var calls []struct {
		Ctx    context.Context
		Config *KvClientConfig
	}
	mock.lockNewKvClient.RLock()
	calls = mock.calls.NewKvClient
	mock.lockNewKvClient.RUnlock()
	return calls
}
