// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package gocbcorex

import (
	"context"
	"sync"
)

// Ensure, that KvClientPoolMock does implement KvClientPool.
// If this is not the case, regenerate this file with moq.
var _ KvClientPool = &KvClientPoolMock{}

// KvClientPoolMock is a mock implementation of KvClientPool.
//
//	func TestSomethingThatUsesKvClientPool(t *testing.T) {
//
//		// make and configure a mocked KvClientPool
//		mockedKvClientPool := &KvClientPoolMock{
//			CloseFunc: func() error {
//				panic("mock out the Close method")
//			},
//			GetClientFunc: func(ctx context.Context) (KvClient, error) {
//				panic("mock out the GetClient method")
//			},
//			ReconfigureFunc: func(opts KvClientPoolConfig)  {
//				panic("mock out the Reconfigure method")
//			},
//		}
//
//		// use mockedKvClientPool in code that requires KvClientPool
//		// and then make assertions.
//
//	}
type KvClientPoolMock struct {
	// CloseFunc mocks the Close method.
	CloseFunc func() error

	// GetClientFunc mocks the GetClient method.
	GetClientFunc func(ctx context.Context) (KvClient, error)

	// ReconfigureFunc mocks the Reconfigure method.
	ReconfigureFunc func(opts KvClientPoolConfig)

	// calls tracks calls to the methods.
	calls struct {
		// Close holds details about calls to the Close method.
		Close []struct {
		}
		// GetClient holds details about calls to the GetClient method.
		GetClient []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Reconfigure holds details about calls to the Reconfigure method.
		Reconfigure []struct {
			// Opts is the opts argument value.
			Opts KvClientPoolConfig
		}
	}
	lockClose       sync.RWMutex
	lockGetClient   sync.RWMutex
	lockReconfigure sync.RWMutex
}

// Close calls CloseFunc.
func (mock *KvClientPoolMock) Close() error {
	if mock.CloseFunc == nil {
		panic("KvClientPoolMock.CloseFunc: method is nil but KvClientPool.Close was just called")
	}
	callInfo := struct {
	}{}
	mock.lockClose.Lock()
	mock.calls.Close = append(mock.calls.Close, callInfo)
	mock.lockClose.Unlock()
	return mock.CloseFunc()
}

// CloseCalls gets all the calls that were made to Close.
// Check the length with:
//
//	len(mockedKvClientPool.CloseCalls())
func (mock *KvClientPoolMock) CloseCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockClose.RLock()
	calls = mock.calls.Close
	mock.lockClose.RUnlock()
	return calls
}

// GetClient calls GetClientFunc.
func (mock *KvClientPoolMock) GetClient(ctx context.Context) (KvClient, error) {
	if mock.GetClientFunc == nil {
		panic("KvClientPoolMock.GetClientFunc: method is nil but KvClientPool.GetClient was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetClient.Lock()
	mock.calls.GetClient = append(mock.calls.GetClient, callInfo)
	mock.lockGetClient.Unlock()
	return mock.GetClientFunc(ctx)
}

// GetClientCalls gets all the calls that were made to GetClient.
// Check the length with:
//
//	len(mockedKvClientPool.GetClientCalls())
func (mock *KvClientPoolMock) GetClientCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetClient.RLock()
	calls = mock.calls.GetClient
	mock.lockGetClient.RUnlock()
	return calls
}

// Reconfigure calls ReconfigureFunc.
func (mock *KvClientPoolMock) Reconfigure(opts KvClientPoolConfig) {
	if mock.ReconfigureFunc == nil {
		panic("KvClientPoolMock.ReconfigureFunc: method is nil but KvClientPool.Reconfigure was just called")
	}
	callInfo := struct {
		Opts KvClientPoolConfig
	}{
		Opts: opts,
	}
	mock.lockReconfigure.Lock()
	mock.calls.Reconfigure = append(mock.calls.Reconfigure, callInfo)
	mock.lockReconfigure.Unlock()
	mock.ReconfigureFunc(opts)
}

// ReconfigureCalls gets all the calls that were made to Reconfigure.
// Check the length with:
//
//	len(mockedKvClientPool.ReconfigureCalls())
func (mock *KvClientPoolMock) ReconfigureCalls() []struct {
	Opts KvClientPoolConfig
} {
	var calls []struct {
		Opts KvClientPoolConfig
	}
	mock.lockReconfigure.RLock()
	calls = mock.calls.Reconfigure
	mock.lockReconfigure.RUnlock()
	return calls
}
