// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package core

import (
	"context"
	"sync"
)

// Ensure, that KvClientPoolMock does implement KvClientPool.
// If this is not the case, regenerate this file with moq.
var _ KvClientPool = &KvClientPoolMock{}

// KvClientPoolMock is a mock implementation of KvClientPool.
//
//	func TestSomethingThatUsesKvClientPool(t *testing.T) {
//
//		// make and configure a mocked KvClientPool
//		mockedKvClientPool := &KvClientPoolMock{
//			GetClientFunc: func(ctx context.Context) (KvClient, error) {
//				panic("mock out the GetClient method")
//			},
//			ReconfigureFunc: func(config *KvClientPoolConfig) error {
//				panic("mock out the Reconfigure method")
//			},
//			ShutdownClientFunc: func(client KvClient)  {
//				panic("mock out the ShutdownClient method")
//			},
//		}
//
//		// use mockedKvClientPool in code that requires KvClientPool
//		// and then make assertions.
//
//	}
type KvClientPoolMock struct {
	// GetClientFunc mocks the GetClient method.
	GetClientFunc func(ctx context.Context) (KvClient, error)

	// ReconfigureFunc mocks the Reconfigure method.
	ReconfigureFunc func(config *KvClientPoolConfig) error

	// ShutdownClientFunc mocks the ShutdownClient method.
	ShutdownClientFunc func(client KvClient)

	// calls tracks calls to the methods.
	calls struct {
		// GetClient holds details about calls to the GetClient method.
		GetClient []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Reconfigure holds details about calls to the Reconfigure method.
		Reconfigure []struct {
			// Config is the config argument value.
			Config *KvClientPoolConfig
		}
		// ShutdownClient holds details about calls to the ShutdownClient method.
		ShutdownClient []struct {
			// Client is the client argument value.
			Client KvClient
		}
	}
	lockGetClient      sync.RWMutex
	lockReconfigure    sync.RWMutex
	lockShutdownClient sync.RWMutex
}

// GetClient calls GetClientFunc.
func (mock *KvClientPoolMock) GetClient(ctx context.Context) (KvClient, error) {
	if mock.GetClientFunc == nil {
		panic("KvClientPoolMock.GetClientFunc: method is nil but KvClientPool.GetClient was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockGetClient.Lock()
	mock.calls.GetClient = append(mock.calls.GetClient, callInfo)
	mock.lockGetClient.Unlock()
	return mock.GetClientFunc(ctx)
}

// GetClientCalls gets all the calls that were made to GetClient.
// Check the length with:
//
//	len(mockedKvClientPool.GetClientCalls())
func (mock *KvClientPoolMock) GetClientCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockGetClient.RLock()
	calls = mock.calls.GetClient
	mock.lockGetClient.RUnlock()
	return calls
}

// Reconfigure calls ReconfigureFunc.
func (mock *KvClientPoolMock) Reconfigure(config *KvClientPoolConfig) error {
	if mock.ReconfigureFunc == nil {
		panic("KvClientPoolMock.ReconfigureFunc: method is nil but KvClientPool.Reconfigure was just called")
	}
	callInfo := struct {
		Config *KvClientPoolConfig
	}{
		Config: config,
	}
	mock.lockReconfigure.Lock()
	mock.calls.Reconfigure = append(mock.calls.Reconfigure, callInfo)
	mock.lockReconfigure.Unlock()
	return mock.ReconfigureFunc(config)
}

// ReconfigureCalls gets all the calls that were made to Reconfigure.
// Check the length with:
//
//	len(mockedKvClientPool.ReconfigureCalls())
func (mock *KvClientPoolMock) ReconfigureCalls() []struct {
	Config *KvClientPoolConfig
} {
	var calls []struct {
		Config *KvClientPoolConfig
	}
	mock.lockReconfigure.RLock()
	calls = mock.calls.Reconfigure
	mock.lockReconfigure.RUnlock()
	return calls
}

// ShutdownClient calls ShutdownClientFunc.
func (mock *KvClientPoolMock) ShutdownClient(client KvClient) {
	if mock.ShutdownClientFunc == nil {
		panic("KvClientPoolMock.ShutdownClientFunc: method is nil but KvClientPool.ShutdownClient was just called")
	}
	callInfo := struct {
		Client KvClient
	}{
		Client: client,
	}
	mock.lockShutdownClient.Lock()
	mock.calls.ShutdownClient = append(mock.calls.ShutdownClient, callInfo)
	mock.lockShutdownClient.Unlock()
	mock.ShutdownClientFunc(client)
}

// ShutdownClientCalls gets all the calls that were made to ShutdownClient.
// Check the length with:
//
//	len(mockedKvClientPool.ShutdownClientCalls())
func (mock *KvClientPoolMock) ShutdownClientCalls() []struct {
	Client KvClient
} {
	var calls []struct {
		Client KvClient
	}
	mock.lockShutdownClient.RLock()
	calls = mock.calls.ShutdownClient
	mock.lockShutdownClient.RUnlock()
	return calls
}
