// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package cbauthx

import (
	"context"
	"crypto/tls"
	"sync"
)

// Ensure, that CertCheckMock does implement CertCheck.
// If this is not the case, regenerate this file with moq.
var _ CertCheck = &CertCheckMock{}

// CertCheckMock is a mock implementation of CertCheck.
//
//	func TestSomethingThatUsesCertCheck(t *testing.T) {
//
//		// make and configure a mocked CertCheck
//		mockedCertCheck := &CertCheckMock{
//			CheckCertificateFunc: func(ctx context.Context, connState *tls.ConnectionState) (UserInfo, error) {
//				panic("mock out the CheckCertificate method")
//			},
//		}
//
//		// use mockedCertCheck in code that requires CertCheck
//		// and then make assertions.
//
//	}
type CertCheckMock struct {
	// CheckCertificateFunc mocks the CheckCertificate method.
	CheckCertificateFunc func(ctx context.Context, connState *tls.ConnectionState) (UserInfo, error)

	// calls tracks calls to the methods.
	calls struct {
		// CheckCertificate holds details about calls to the CheckCertificate method.
		CheckCertificate []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ConnState is the connState argument value.
			ConnState *tls.ConnectionState
		}
	}
	lockCheckCertificate sync.RWMutex
}

// CheckCertificate calls CheckCertificateFunc.
func (mock *CertCheckMock) CheckCertificate(ctx context.Context, connState *tls.ConnectionState) (UserInfo, error) {
	if mock.CheckCertificateFunc == nil {
		panic("CertCheckMock.CheckCertificateFunc: method is nil but CertCheck.CheckCertificate was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ConnState *tls.ConnectionState
	}{
		Ctx:       ctx,
		ConnState: connState,
	}
	mock.lockCheckCertificate.Lock()
	mock.calls.CheckCertificate = append(mock.calls.CheckCertificate, callInfo)
	mock.lockCheckCertificate.Unlock()
	return mock.CheckCertificateFunc(ctx, connState)
}

// CheckCertificateCalls gets all the calls that were made to CheckCertificate.
// Check the length with:
//
//	len(mockedCertCheck.CheckCertificateCalls())
func (mock *CertCheckMock) CheckCertificateCalls() []struct {
	Ctx       context.Context
	ConnState *tls.ConnectionState
} {
	var calls []struct {
		Ctx       context.Context
		ConnState *tls.ConnectionState
	}
	mock.lockCheckCertificate.RLock()
	calls = mock.calls.CheckCertificate
	mock.lockCheckCertificate.RUnlock()
	return calls
}
